# Kakao 설정
kakao:
  client-id: ab413dab6893dc04de3a8dd27012ca74
  redirect-uri: http://localhost:3000

# secret Key
custom:
  jwt:
    secretKey: vdXLJtWncbG7vtVxPnoaJNaqIxqguyd3W4a3vaXcy2CSlhXXoD8O3u5ijSqHW1Ly3TT1E/978eh8izYDBC30gw==